### ISSUE TITLE
Missing a bunch of scripts in the Script/Data folder

### ISSUE THREAD

**Issue by EvoPulseGaming** [Terohnon/RobinhoodDesktop#1]

**Comment by EvoPulseGaming** [comment]
RobinhoodDesktop\RobinhoodDesktop\RobinhoodDesktop\Script\Data\
missing Trend.cs, Volatility.cs, ConsecutiveDirection.cs, LineOfBestFits.cs, TimeToChange.cs

**Comment by Terohnon** [comment]
Sorry about that. Those scripts haven't been proven out yet, so I'm holding off on committing them for now. I've removed the reference to them from the solution. The rest of the project should build now.

I haven't updated RobinhoodNet to the latest authentication format yet, so I don't think it will currently be able to log into an account. Just a heads-up.

**Comment by EvoPulseGaming** [comment]
I already fixed the login stuff and did some other things. The login could be setup better, but it works
https://github.com/EvoPulseGaming/RobinhoodDesktop/commits/master
